### ISSUE TITLE
OAuth Authorization

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#203]
Creating an issue to track progress on OAuth integration with farmOS.

The relevant Drupal issue is here: https://www.drupal.org/project/farm/issues/3034214

- [x] Integrate Drupal 7 `oauth2_server` module with Drupal permissions
- [x] Create an OAuth Client for the farmOS API #207 
- [x] Create a customized `authorized` page for the farmOS API Client #207 
- [x] Document support for OAuth in farmOS farmOS/farmOS.org#61
- [ ] Add OAuth support to farmOS.py farmOS/farmOS.py#18
- [x] Integrate with farmOS Aggregator - farmOS/farmOS-aggregator#20
- [ ] Add OAuth support to farmOS.js
- [ ] Integrate with Field Kit - farmOS/farmOS-client#311
- [ ] Create migration plan from D7 to D8

**Comment by paul121** [comment]
- [ ] Integrate Drupal 7 `oauth2_server` module with Drupal permissions
- [ ] Create an OAuth Client for the farmOS API
- [ ] Create a customized `authorized` page for the farmOS API Client
- [ ] Document farmOS OAuth Flows
- [ ] Add OAuth support to farmOS.py
- [ ] Add OAuth support to farmOS.js
- [ ] Integrate with farmOS Aggreagator
- [ ] Integrate with Field Kit

**Comment by paul121** [comment]
We have found a way to integrate `oauth2_server` with Drupal Permissions using the `restws` module. A new Drupal Contrib module [`restws_oauth2_server`](https://www.drupal.org/project/restws_oauth2_server) adds this integration.

I've drafted the [`farm_api_oauth`](https://github.com/paul121/farm_api_oauth/) module which creates an OAuth Server with a Client for the farmOS API. It also uses the `restws_oauth2_server` config to set the default OAuth Scope used to authenticate OAuth Tokens to Drupal Users. It also creates an `authorized` callback page to help with the Authorization flow - it is basic right now, and could be improved.

**Comment by paul121** [comment]
I've updated the description to mark the following as complete:
 - Integrate `oauth2_server` with farmOS core `farm_api` module
 - Create OAuth client(s) for farmOS
 - Document OAuth Authorization and Authentication
 - Integrate with farmOS Aggregator

Still to-do: 
 - It would be great to get full integration tests in farmOS.py and farmOS Aggregator that use the OAuth Authorization flows. This is a bit complex but would be a great thing to automate within tests
- Integrate with farmOS.js and Field Kit
- Create migration plan from D7 to D8

**Comment by mstenta** [comment]
Let's close this issue and spin up other issues if we need them. farmOS OAuth authorization is complete, generally speaking.

> It would be great to get full integration tests in farmOS.py and farmOS Aggregator that use the OAuth Authorization flows. This is a bit complex but would be a great thing to automate within tests

Maybe make a new issue for this in the Aggregator queue?

> Integrate with farmOS.js and Field Kit

This will be covered soon in https://github.com/farmOS/farmOS-client/issues/311 (which will also involve adding support in farmOS.js).

> Create migration plan from D7 to D8

I'll spin up an issue for this soon... I hope to tackle OAuth2 stuff early on in the farmOS 2.0.x development process, so this will happen naturally.
